### ISSUE TITLE
use zod for validation in all files

### ISSUE THREAD

**Issue by subediaakash** [devsargam/internsathi-api#10]

**Comment by rehan-adi** [comment]
I've added Zod validation to all relevant files. Please review the changes in PR #10.

**Comment by devsargam** [comment]
Thank you sir.

**Comment by rehan-adi** [comment]
@devsargam Bro what about the swagger docs issue ? can you assign that to me

**Comment by devsargam** [comment]
@rehan-adi do u want to do it? It's quite hard to finish actually but can do it

**Comment by rehan-adi** [comment]
I will do it man, can you check your email....

and assign that issue to me
